### ISSUE TITLE
Sending to an already used address is possible

### ISSUE THREAD

**Issue by ds2216** [SemkoDev/romeo.html#4]
I tested sending 1i to an address that already spent IOTAs and it was possibly. Should be prevented, like it is in the Light Wallet. 

https://thetangle.org/address/EUYSCJFJDLIVBO9IEPHBDOKKMYJRUONETHAEPIAMOYY9LFJM9MIHBDMGNDAFCBXAHL9JEABRNMRYDWCWZ

**Comment by romansemko** [comment]
Yup. It's on the roadmap. The same for using spent addresses with positive balance as outputs.

Thanks!

**Comment by romansemko** [comment]
Added check for sent addresses. An error message is shown on send to such an address.
It is not enforced, however, for certain edge cases.
