### ISSUE TITLE
QR Code Generation Issue

### ISSUE THREAD

**Issue by yippykaiyay012** [SemkoDev/romeo.html#5]
QR Codes generated cannot be used.

Address that exists is :
CPPCCRRRPOOMFTCXJFYS9HOEQOIDNPNEYEIVAUHNHKMUXKNUJINCYOYRBVIJZQHGJTRAYSDRPWR9DRNGZVNTYXDVXB

QR Code is :
CPPCCRRRPOOMFTCXJFYS9HOEQOIDNPNEYEIVAUHNHKMUXKNUJINCYOYRBVIJZQHGJTRAYSDRPWR9DRNGZ

**Comment by romansemko** [comment]
The checksum was missing. Fixed. Will be available in the next release!
