### ISSUE TITLE
Syncing seems stuck

### ISSUE THREAD

**Issue by gjeee** [SemkoDev/romeo.html#6]
A lot of times the sync loop seems stuck. From a GUI perspective at least. You see the icons turning continuously. (Firefox v59)

**Comment by gjeee** [comment]
Further: it happens a lot that the initial sync does not update the balance (it stays 0).

**Comment by romansemko** [comment]
I think, this might have to do with API throttling on the Field server. Can you check next time in the network console if you see any 4XX responses from field.carriota.com?

Regarding initial sync: noted. Thanks! The initial sync was just loading the cache and waited 3 minutes before next round of online-sync. I changed that the pages list and current page are directly synced with remote on load. Will be in the next release.

**Comment by gjeee** [comment]
in v1.0.5 the "continuous-sync" seems to not happen anymore. i also did not encounter any 4xxx responses in network logs. so i guess we can close this issue.
